### ISSUE TITLE
Not able to start application

### ISSUE THREAD

**Issue by ondrejbartas** [IBM-Cloud/get-started-aspnet-core#1]
Hi,

when I try to run `dotnet restore` I am getting error:

`src/GetStartedDotnet' does not contain a project to restore.

do you have any idea why?

**Comment by itzunagi** [comment]
@ondrejbartas Are you using SDK version `1.0.0-preview4-004233`?  You can check by running `dotnet --version` from within the project folder.

You should see this:

    C:\dev\get-started-aspnet-core\src\GetStartedDotnet>dotnet --version
    1.0.0-preview4-004233

**Comment by ondrejbartas** [comment]
using preview 2. it seems that you need to have project.json

**Comment by itzunagi** [comment]
@ondrejbartas Yes, the preview2 tooling requires project.json (and VS2015).  This sample is for the latest (MSBuild) tooling using VS2017.

**Comment by ondrejbartas** [comment]
ok thanks for clarification. Will try it.

**Comment by funky81** [comment]
Hi @degrim , therefore I have to open it using vs2017? 
If I want to use vs2015, i have to create project.json?

**Comment by itzunagi** [comment]
@funky81 Yes, but the project.json format is deprecated now that VS2017 is released and will eventually be removed from the buildpack.

**Comment by toanxyz** [comment]
I created the new project with .aspnetcore1.0 using VS2017, when I deployed to IBM Bluemix and the result is "404 not found: Requested route ('app.domain') does not exist"

**Comment by rvennam** [comment]
@nmtoan07 type `cf apps` to see the URL for your apps. If you changed your manifest.yml file, please share that as well

**Comment by itzunagi** [comment]
@nmtoan07 The default templates in VS2017 will not make the app listen on the right port, they will be listening on the default port of 5000 instead, so they will not be accessible.  To use those templates you will need to modify the `Main` method to be like the [`Main`](https://github.com/IBM-Bluemix/get-started-aspnet-core/blob/master/src/GetStartedDotnet/Program.cs#L11) method of the app in this repo.

**Comment by toanxyz** [comment]
@degrim base on your main file I make it works! Thanks for your help.
I want to explain in detail how I fixed it.
I created a ASP.NET Core 1.0 with Visual 2017, web mvc template.
After that, we need to install the nuget package for the extension method: AddCommandLine
`Microsoft.Extensions.Configuration.CommandLine`
The Program.cs:

```
public class Program
    {
        public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseConfiguration(config)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();
        }
    }
```
The important configuration is .UseConfiguration(config). Without this configuration, the application will start on the locahost:5000 and it will not work.
In the runtime, Bluemix will use command config to setup the PORT and other things.
The working log should be `Now listening on: http://0.0.0.0:8080`

I also created a sample project at this [link](https://github.com/nmtoan07/bluemix-aspnetcore-starter) and it was deployed successful [here](https://aspnetcore-starter.mybluemix.net/). Hope it helps for everyone.

Now everything's ok, next step I will deploy my real product to IBM Bluemix.

Thank you all!

**Comment by itzunagi** [comment]
@nmtoan07 That information is also available in the [Bluemix documentation](https://console.bluemix.net/docs/runtimes/dotnet/index.html#application_configuration).

**Comment by toanxyz** [comment]
@degrim Many thanks.
For the default package in Bluemix console, do we have any plan to update it? It seems still use the preview version of .net core and buildpack. So I need to update the buildpack, configuration, etc. It was a little bit confusing between the document, the generated source on blumix console and the github repos.

**Comment by itzunagi** [comment]
@nmtoan07 The default app will be updated in Bluemix after the buildpack is updated, the changes have already been made in the [develop branch](https://github.com/IBM-Bluemix/aspnet-core-helloworld/tree/develop) of the repository for that app.

**Comment by itzunagi** [comment]
Closing this as it has been inactive and the original issue was resolved.
