### ISSUE TITLE
404 messages when running localy

### ISSUE THREAD

**Issue by decapo01** [IBM-Cloud/get-started-aspnet-core#3]
I cloned and ran this app localy and for the index page and another route I created I get a 404 error when running on my local machine.  The api route does yield a messgae and is not 404.  Also when I deploy to bluemix everything works as expected.  It's only on the local machine that I experience this problem.

**Comment by itzunagi** [comment]
@decapo01 The project expects to be run from within the `src\GetStartedDotnet` folder as indicated in step 2 in the Readme.  Running from VS2017 should also work.  Running it from the solution folder with `dotnet run -p src\GetStartedDotnet\GetStartedDotnet.csproj` will result in the Views folder not being found.

**Comment by decapo01** [comment]
I'm running it from the ```src/GettingStartedDotnet``` directory.  I had to add 

```using System.IO;```
and add
```.UseContentRoot(Directory.GetCurrentDirectory())```

to the start up chain to get it to work.  I should add that I'm on ubuntu linux 14.04.

So my full Program.cs start chain is 

```
public static void Main(string[] args)                        
        {                                                             
            var host = new WebHostBuilder()                           
                .UseKestrel()                                         
                .UseContentRoot(Directory.GetCurrentDirectory())      
                .UseStartup<Startup>()                                
                .Build();                                             
            host.Run();                                               
        }
```

just to note the template from the ```dotnet new mvc``` command currently is 

```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

where you have to add ```using Microsoft.AspNetCore.Hosting;```

Doing this also worked.
